import { useState } from 'react';
import type { User } from 'firebase/auth';
import { Cloud, LogOut, RefreshCw, UserRound } from 'lucide-react';

interface AuthControlsProps { user: User | null; syncStatus: 'synced' | 'syncing' | 'offline'; onSignIn: () => void; onSignOut: () => void; busy: boolean; }
export function AuthControls({ user, syncStatus, onSignIn, onSignOut, busy }: AuthControlsProps) {
  const [open, setOpen] = useState(false);
  const statusLabel = syncStatus === 'synced' ? 'Synced' : syncStatus === 'syncing' ? 'Syncing' : 'Offline';
  const statusColor = syncStatus === 'synced' ? 'bg-emerald-400' : syncStatus === 'syncing' ? 'bg-amber-400' : 'bg-rose-400';
  if (!user) return <button type="button" onClick={onSignIn} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-semibold text-slate-800 shadow-sm transition hover:bg-slate-100 disabled:opacity-60"><Cloud className="h-3.5 w-3.5 text-indigo-500" />{busy ? 'Signing in…' : 'Sign in with Google'}</button>;
  return <div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-900/80 p-1.5 text-slate-200"><img className="h-7 w-7 rounded-lg object-cover" src={user.photoURL ?? ''} alt="" onError={(event) => { event.currentTarget.style.display = 'none'; }} /><UserRound className="h-5 w-5" aria-hidden="true" /><span className="hidden max-w-28 truncate text-xs font-semibold sm:inline">{user.displayName ?? 'Account'}</span></button>{open && <div className="fixed inset-x-4 bottom-20 z-50 rounded-2xl border border-slate-700 bg-slate-900 p-5 shadow-2xl sm:absolute sm:inset-auto sm:right-0 sm:top-12 sm:w-80"><div className="flex items-center gap-3"><img className="h-10 w-10 rounded-xl object-cover" src={user.photoURL ?? ''} alt="" /><div className="min-w-0"><p className="truncate text-sm font-bold text-white">{user.displayName ?? 'CareerOS account'}</p><p className="truncate text-xs text-slate-400">{user.email}</p></div></div><div className="my-4 border-t border-slate-800" /><div className="flex items-center justify-between text-sm text-slate-300"><span className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${statusColor}`} />Cloud status</span><span>{statusLabel}</span></div><p className="mt-3 text-xs text-slate-500">Storage: Cloud Account</p><button type="button" onClick={onSignOut} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-800 px-3 py-2.5 text-sm font-semibold text-slate-200 hover:bg-slate-700"><LogOut className="h-4 w-4" />Sign out</button></div>}</div>;
}
