import { CheckCircle2, Sparkles, Wrench } from 'lucide-react';
import { PRODUCT_VERSION } from '../utils/productExperience';

const entries = [
  { title: `Version ${PRODUCT_VERSION}`, date: 'July 2026', icon: Sparkles, color: 'text-indigo-300', sections: [{ label: 'New', items: ['Notification Center', 'Global search and command palette', 'First-time onboarding'] }, { label: 'Improved', items: ['Profile completion guidance', 'Dashboard quick actions'] }, { label: 'Fixed', items: ['More helpful workspace empty states'] }] },
];

export default function ChangelogView() {
  return <div className="mx-auto max-w-3xl space-y-8 px-4 py-6 sm:px-6 lg:px-8"><header><p className="text-xs font-semibold uppercase tracking-widest text-indigo-400">Product updates</p><h1 className="mt-2 font-display text-3xl font-bold text-white">Changelog</h1><p className="mt-2 text-sm text-slate-400">A concise record of improvements to CareerOS Lite.</p></header>{entries.map((entry) => { const Icon = entry.icon; return <article key={entry.title} className="rounded-3xl border border-slate-800 bg-slate-900/70 p-6"><div className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl bg-slate-800 ${entry.color}`}><Icon className="h-5 w-5" /></span><div><h2 className="font-display text-xl font-bold text-white">{entry.title}</h2><p className="text-xs text-slate-500">{entry.date}</p></div></div><div className="mt-6 space-y-5">{entry.sections.map((section) => <div key={section.label}><h3 className="flex items-center gap-2 text-sm font-semibold text-slate-200">{section.label === 'Improved' ? <CheckCircle2 className="h-4 w-4 text-emerald-400" /> : section.label === 'Fixed' ? <Wrench className="h-4 w-4 text-amber-400" /> : <Sparkles className="h-4 w-4 text-indigo-300" />}{section.label}</h3><ul className="mt-2 space-y-1.5 pl-6 text-sm text-slate-400">{section.items.map((item) => <li key={item} className="list-disc">{item}</li>)}</ul></div>)}</div></article>; })}</div>;
}
