import { Search, Users } from 'lucide-react';
import type { AdminUserSummary } from './analyticsMetrics';

export type UserRange = 'today' | 'week' | 'month' | 'all';

const dateLabel = (value: Date | null) => value ? value.toLocaleDateString() : '—';

export function UserDirectory({ users, query, range, onQueryChange, onRangeChange, onSelect }: { users: AdminUserSummary[]; query: string; range: UserRange; onQueryChange: (value: string) => void; onRangeChange: (value: UserRange) => void; onSelect: (user: AdminUserSummary) => void }) {
  return <section className="rounded-2xl border border-slate-800 bg-slate-900/70 shadow-sm">
    <div className="flex flex-col gap-4 border-b border-slate-800 p-5 lg:flex-row lg:items-center lg:justify-between">
      <div><h2 className="text-base font-semibold text-slate-100">Users</h2><p className="mt-1 text-sm text-slate-400">Identity, activity, and session health.</p></div>
      <div className="flex flex-col gap-2 sm:flex-row"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" /><input aria-label="Search users" value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Search name or email" className="h-10 w-full rounded-lg border border-slate-700 bg-slate-950 pl-9 pr-3 text-sm text-slate-100 outline-none placeholder:text-slate-600 focus:border-indigo-400 sm:w-56" /></label><select aria-label="Filter users by joined date" value={range} onChange={(event) => onRangeChange(event.target.value as UserRange)} className="h-10 rounded-lg border border-slate-700 bg-slate-950 px-3 text-sm text-slate-200 outline-none focus:border-indigo-400"><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="all">All</option></select></div>
    </div>
    <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="border-b border-slate-800 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3 font-medium">User</th><th className="px-4 py-3 font-medium">Provider</th><th className="px-4 py-3 font-medium">Joined</th><th className="px-4 py-3 font-medium">Last seen</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 text-right font-medium">Sessions</th></tr></thead><tbody>{users.map((user) => <tr key={user.uid} tabIndex={0} role="button" onClick={() => onSelect(user)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') onSelect(user); }} className="cursor-pointer border-b border-slate-800/80 text-slate-300 transition hover:bg-slate-800/50 focus:bg-slate-800/50 focus:outline-none"><td className="px-5 py-4"><div className="flex items-center gap-3">{user.photoURL ? <img src={user.photoURL} alt="" className="h-9 w-9 rounded-full object-cover" /> : <div className="flex h-9 w-9 items-center justify-center rounded-full bg-indigo-500/15 text-xs font-semibold text-indigo-200">{(user.displayName ?? user.email ?? '?').slice(0, 1).toUpperCase()}</div>}<div><p className="font-medium text-slate-100">{user.displayName ?? 'Unnamed user'}</p><p className="text-xs text-slate-500">{user.email ?? user.uid}</p></div></div></td><td className="px-4 py-4 text-slate-400">{user.providerId.replace('.com', '')}</td><td className="px-4 py-4 text-slate-400">{dateLabel(user.joinedAt)}</td><td className="px-4 py-4 text-slate-400">{dateLabel(user.lastSeenAt)}</td><td className="px-4 py-4"><span className={`inline-flex items-center gap-1.5 text-xs ${user.status === 'online' ? 'text-emerald-300' : 'text-slate-500'}`}><span className={`h-2 w-2 rounded-full ${user.status === 'online' ? 'bg-emerald-400' : 'bg-slate-600'}`} />{user.status}</span></td><td className="px-4 py-4 text-right font-medium text-slate-200">{user.totalSessions}</td></tr>)}</tbody></table></div>
    {users.length === 0 && <div className="flex items-center justify-center gap-2 p-10 text-sm text-slate-500"><Users className="h-4 w-4" />No users match this filter.</div>}
  </section>;
}
