import { X } from 'lucide-react';
import type { AdminActivity, AdminUserSummary } from './analyticsMetrics';
import { providerLabel, relativeTime, userLabel } from './adminFormatters';

const duration = (value: number) => value ? `${Math.round(value / 1000)}s` : '—';
const dateTime = (value: Date | null) => value ? value.toLocaleString() : '—';

export function UserProfileDrawer({ user, activities, onClose }: { user: AdminUserSummary | null; activities: AdminActivity[]; onClose: () => void }) {
  if (!user) return null;
  const stats = [['Sessions', user.totalSessions], ['Avg. session', duration(user.averageSessionMs)], ['AI conversations', user.conversations], ['Goals created', user.goalsCreated], ['Certificates', user.certificates], ['Journey entries', user.journeyEntries], ['Notes', user.notes]];
  const userActivities = activities.filter((activity) => activity.userId === user.uid);
  return <div className="fixed inset-0 z-50 bg-slate-950/65" role="presentation" onMouseDown={onClose}><aside role="dialog" aria-modal="true" aria-label="User profile" onMouseDown={(event) => event.stopPropagation()} className="ml-auto h-full w-full max-w-xl overflow-y-auto border-l border-slate-800 bg-slate-950 p-6 shadow-2xl"><div className="flex items-start justify-between"><div className="flex items-center gap-3">{user.photoURL ? <img src={user.photoURL} alt="" className="h-12 w-12 rounded-full object-cover" /> : <div className="flex h-12 w-12 items-center justify-center rounded-full bg-indigo-500/15 text-lg font-semibold text-indigo-200">{userLabel(user).slice(0, 1).toUpperCase()}</div>}<div><h2 className="text-lg font-semibold text-white">{userLabel(user)}</h2><p className="text-sm text-slate-400">{user.email ?? user.uid}</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Close user profile"><X className="h-5 w-5" /></button></div><dl className="mt-7 grid gap-x-5 gap-y-4 text-sm sm:grid-cols-2">{[['UID', user.uid], ['Provider', providerLabel(user.providerId)], ['Joined', dateTime(user.joinedAt)], ['Last login', dateTime(user.lastLoginAt)], ['Last seen', dateTime(user.lastSeenAt)], ['Last active', dateTime(user.lastActiveAt)], ['Current status', user.status]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-slate-200">{value}</dd></div>)}</dl><div className="mt-8 grid grid-cols-2 gap-3">{stats.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-800 bg-slate-900/70 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold text-slate-100">{value}</p></div>)}</div><section className="mt-8"><h3 className="text-sm font-semibold text-slate-100">Latest activity</h3><ol className="mt-3 divide-y divide-slate-800 rounded-xl border border-slate-800 bg-slate-900/40">{userActivities.slice(0, 10).map((activity) => <li key={activity.id} className="flex justify-between gap-4 p-3"><div><p className="text-sm text-slate-200">{activity.action}</p><p className="text-xs text-slate-500">{activity.page}</p></div><time className="shrink-0 text-xs text-slate-500" title={activity.timestamp.toLocaleString()}>{relativeTime(activity.timestamp)}</time></li>)}{!userActivities.length && <li className="p-4 text-sm text-slate-500">No tracked activity yet.</li>}</ol></section></aside></div>;
}
